server:
  port: 8084

spring:
  application:
    name: comprovante-notificacao
  kafka:
    bootstrap-servers: ${KAFKA:localhost:9092}
    consumer:
      group-id: notificacao
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: br.com.caixa.pix.contracts
        spring.json.value.default.type: br.com.caixa.pix.contracts.ComprovanteGravadoEvent
    producer:   # @RetryableTopic publica nos tópicos de retry/DLT
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  circuitbreaker:
    instances:
      notificacao-gateway:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
