server:
  port: 8083

spring:
  application:
    name: comprovante-consulta
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

gravador:
  base-url: ${GRAVADOR_BASE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
